// Staying up to date in the BROWSER, without ever serving a half-updated app.
//
// The native app has done this for a while (src/app/ota.ts + src/worker/ota.ts):
// ask an endpoint for the current version, download in the background, swap
// when it is safe. This is the same story for the web, reusing the same
// endpoint and the same "when is it safe" policy (src/app/updatePolicy.ts) so
// there is exactly ONE meaning of "current version" across both platforms.
//
// ---------------------------------------------------------------------------
// Where atomicity actually comes from
// ---------------------------------------------------------------------------
// We do NOT hand-roll a downloader. The service worker generated by
// vite-plugin-pwa/workbox already gives us an all-or-nothing transaction, and
// it is a much stronger one than we could write:
//
//   * A new sw.js precaches EVERY app-shell URL during its `install` event.
//   * If any one of those fetches fails — dropped connection, quota exhausted
//     mid-write, a 5xx — `install` rejects, the new worker is discarded, and it
//     never reaches the `waiting` state.
//   * The OLD worker keeps serving its OWN complete precache the entire time.
//
// So `registration.waiting !== null` is the atomicity signal: it means the
// whole set landed. Our job is not to re-implement that, it is to **never
// pre-empt it**. Concretely:
//
//   1. Nothing swaps until a waiting worker exists (vite.config.ts sets
//      `skipWaiting: false` / `clientsClaim: false` so the browser cannot flip
//      on its own — see the note there).
//   2. Nothing swaps until the moment is safe (updatePolicy.ts).
//   3. Every other path fails CLOSED. A failure means "keep serving the old
//      version, completely" — which offline-first makes the correct answer
//      anyway, since there may be no network to correct a mistake with.
//
// ---------------------------------------------------------------------------
// The one hole workbox does NOT plug, and why `verifyPrecacheIntegrity` exists
// ---------------------------------------------------------------------------
// wrangler.jsonc sets `not_found_handling: "single-page-application"`, so EVERY
// path on this origin returns 200. A missing `/assets/index-abc123.js` does not
// 404 — it returns `index.html` with status 200 and `content-type: text/html`.
// Workbox checks status, not content, so it would cache that HTML under a .js
// URL, `install` would SUCCEED, and we would swap into an app whose entry
// script is a copy of the page. Offline-first then makes it permanent: the
// service worker serves that broken combination forever, with no network to
// correct it. That is the catastrophe this feature could otherwise create.
//
// So before swapping we read the precache back and check that what landed
// LOOKS like what was asked for. Cheap, no manifest parsing, and it fails
// closed: an unreadable or empty cache is "do not swap", never "looks fine".

import { decideApply, type UpdateMoment } from './updatePolicy'

// ---------------------------------------------------------------------------
// 1. The version endpoint  (reused: GET /ota/check, src/worker/ota.ts)
// ---------------------------------------------------------------------------

/**
 * The version endpoint. This is the SAME endpoint the installed Android app
 * POSTs to on launch; a GET returns the published manifest. Reused rather than
 * duplicated on purpose — two sources of truth for "what is the current
 * version" is the bug this feature would otherwise introduce.
 *
 * It is a Worker route (`run_worker_first: ["/ota/*"]`), it answers
 * `cache-control: no-store`, and it is in the service worker's
 * `navigateFallbackDenylist` and matches no precache or runtime-cache rule — so
 * the service worker never caches it and can always observe a new version.
 */
export const VERSION_ENDPOINT = '/ota/check'

/** The raw bits of an HTTP response the version check needs. */
export interface HttpProbe {
  readonly ok: boolean
  readonly status: number
  readonly contentType: string | null
  readonly body: string
}

/** Why a version could not be read. Named so failures are diagnosable. */
export type ProbeFailure =
  /** Non-2xx. */
  | 'http-error'
  /** Status said 200 but this is not JSON — almost always the SPA fallback. */
  | 'not-json'
  /** Claimed to be JSON and was not. */
  | 'unparseable'
  /** Valid JSON, wrong shape. */
  | 'bad-shape'
  /** The endpoint is up but CI has not published a build yet. */
  | 'no-published-build'
  /** A "version" that cannot be one — e.g. a page of HTML in the field. */
  | 'implausible-version'

export type VersionProbe =
  | { readonly kind: 'version'; readonly version: string }
  | { readonly kind: 'unavailable'; readonly why: ProbeFailure }

/** The worker's sentinel for "no manifest has been published". Not a version. */
const NO_BUILD = 'builtin'

/**
 * A build number is a short opaque token (this repo uses the git commit count,
 * see vite.config.ts). Anything with whitespace or markup in it is a response
 * body that got this far by accident, not a version.
 */
const plausibleVersion = (v: string): boolean => v.length > 0 && v.length <= 64 && !/[\s<>]/.test(v)

/**
 * Turn a response from the version endpoint into a version, or into a named
 * reason why there isn't one.
 *
 * **Content is checked, never status.** Under the SPA fallback a missing file
 * comes back as `index.html` with a cheerful 200, so `res.ok` proves nothing at
 * all. We require a JSON content-type, a parse, and the documented shape.
 */
export const parseVersionPayload = (res: HttpProbe): VersionProbe => {
  if (!res.ok) return { kind: 'unavailable', why: 'http-error' }
  // TRAP: the SPA fallback's 200 + text/html dies here, which is the point.
  if (!/\bapplication\/json\b/i.test(res.contentType ?? '')) return { kind: 'unavailable', why: 'not-json' }

  let parsed: unknown
  try {
    parsed = JSON.parse(res.body)
  } catch {
    return { kind: 'unavailable', why: 'unparseable' }
  }

  const current = (parsed as { current?: unknown } | null)?.current
  if (typeof current !== 'object' || current === null) return { kind: 'unavailable', why: 'bad-shape' }
  const version = (current as { version?: unknown }).version
  if (typeof version !== 'string') return { kind: 'unavailable', why: 'bad-shape' }
  if (version === '' || version === NO_BUILD) return { kind: 'unavailable', why: 'no-published-build' }
  if (!plausibleVersion(version)) return { kind: 'unavailable', why: 'implausible-version' }
  return { kind: 'version', version }
}

/**
 * Is the published version something we should update TO?
 *
 * `'dev'` is the fallback baked in when the build-time define did not run, so
 * we cannot meaningfully compare and must not update — otherwise every dev
 * build would think it was permanently out of date.
 */
export const isNewerBuild = (published: string, running: string): boolean =>
  running !== 'dev' && published !== running

// ---------------------------------------------------------------------------
// 2. Verifying the downloaded set before swapping
// ---------------------------------------------------------------------------

/** One entry read back out of the service worker's precache. */
export interface PrecacheEntry {
  /** The cached request URL. May carry workbox's `?__WB_REVISION__=` query. */
  readonly url: string
  /** The cached response's content-type, or null if it had none. */
  readonly contentType: string | null
}

export type IntegrityFailure =
  /** Nothing cached. Never treat "I found no problems" in an empty set as a pass. */
  | 'precache-empty'
  /** No script at all — whatever this is, it is not a bootable app bundle. */
  | 'precache-has-no-script'
  /** Something was stored under a URL whose type it plainly is not. */
  | 'wrong-content-type'
  /** The cache could not be read; we know nothing, so we do nothing. */
  | 'precache-unreadable'

export type IntegrityResult =
  | { readonly ok: true }
  | { readonly ok: false; readonly why: IntegrityFailure; readonly offenders: readonly string[] }

/** Strip the origin and workbox's revision query so entries compare by path. */
export const precachePath = (url: string): string => {
  const noQuery = url.split('?')[0] ?? url
  const schemeEnd = noQuery.indexOf('://')
  if (schemeEnd === -1) return noQuery
  const slash = noQuery.indexOf('/', schemeEnd + 3)
  return slash === -1 ? '/' : noQuery.slice(slash)
}

/**
 * The entries whose integrity actually decides whether the app can boot: the
 * hashed JS/CSS bundle, the shell, and the manifest.
 *
 * The check is deliberately NOT run over themes and icons. Those are art — a
 * bad one is a missing sprite, not a dead app — and including them would mean a
 * single odd content-type anywhere in 400 cached files could stall updates for
 * that client permanently, which is a worse failure than the one being
 * prevented. `precache-has-no-script` still guarantees the set is not empty of
 * the things that matter.
 */
export const isCriticalAsset = (url: string): boolean => {
  const path = precachePath(url)
  return path.startsWith('/assets/') || path === '/index.html' || path.endsWith('.webmanifest')
}

/** What a given extension must look like once it is sitting in the cache. */
const EXPECTED_TYPE: readonly { readonly ext: RegExp; readonly type: RegExp }[] = [
  { ext: /\.m?js$/i, type: /\b(javascript|ecmascript)\b/i },
  { ext: /\.css$/i, type: /\btext\/css\b/i },
  { ext: /\.json$/i, type: /\bjson\b/i },
  { ext: /\.webmanifest$/i, type: /\b(json|manifest)\b/i },
  { ext: /\.(png|webp|svg|ico)$/i, type: /\bimage\/|\bsvg\b/i },
]

/**
 * Check that the freshly precached set is plausibly a whole, real app bundle
 * and not the SPA fallback wearing its URLs.
 *
 * Deliberately fails closed in three ways, because under offline-first a wrong
 * "yes" is permanent and a wrong "no" just means the player stays on a version
 * that works:
 *
 *  - an empty cache is a failure, not a vacuous pass;
 *  - a cache with no script at all is a failure (nothing could boot from it);
 *  - a missing content-type counts against the entry, it is not waved through.
 */
export const verifyPrecacheIntegrity = (entries: readonly PrecacheEntry[]): IntegrityResult => {
  if (entries.length === 0) return { ok: false, why: 'precache-empty', offenders: [] }

  const offenders: string[] = []
  let scripts = 0
  for (const entry of entries) {
    const path = precachePath(entry.url)
    if (/\.m?js$/i.test(path)) scripts++
    const rule = EXPECTED_TYPE.find((r) => r.ext.test(path))
    if (!rule) continue // an extension we make no claim about (e.g. index.html)
    if (!rule.type.test(entry.contentType ?? '')) offenders.push(path)
  }

  if (offenders.length > 0) return { ok: false, why: 'wrong-content-type', offenders }
  if (scripts === 0) return { ok: false, why: 'precache-has-no-script', offenders: [] }
  return { ok: true }
}

// ---------------------------------------------------------------------------
// 3. The coordinator
// ---------------------------------------------------------------------------

/** The installed-but-not-yet-active service worker. */
export interface StagedWorker {
  postMessage(message: unknown): void
}

/** Everything the updater touches, injected so all of it is testable. */
export interface WebUpdaterDeps {
  /** Fetch the version endpoint. REJECTS when offline — that is normal. */
  readonly probe: () => Promise<HttpProbe>
  /** Ask the browser to re-check the origin for a new service worker. */
  readonly checkForWorker: () => Promise<void>
  /** The worker that finished installing and is waiting, or null. */
  readonly waiting: () => StagedWorker | null
  /** Read back every precache entry (url + content-type). */
  readonly precacheEntries: () => Promise<readonly PrecacheEntry[]>
  /** Reload the page. Only ever called after the swap actually happened. */
  readonly reload: () => void
  /** The build number of the code running right now (`APP_VERSION`). */
  readonly appVersion: string
}

/** Coarse outcome of one check. Returned for tests/diagnostics; nothing is shown. */
export type CheckOutcome =
  | 'up-to-date'
  | 'unavailable'
  | 'downloading'
  | 'staged'
  | 'incomplete'
  | 'already-staged'

export interface WebUpdater {
  /** Look for a new version. Never throws, never logs, never blocks the game. */
  check(): Promise<CheckOutcome>
  /** A complete, verified update is downloaded and waiting to be applied. */
  readonly staged: boolean
  /** Tell the updater where the player is. It applies if (and only if) it may. */
  reportMoment(moment: UpdateMoment, peers: number): void
  /** Wire to the SW `statechange`→`installed` event; safe to call repeatedly. */
  onWorkerInstalled(): Promise<CheckOutcome>
  /** Wire to `controllerchange`: the swap landed, so now the reload is real. */
  onControllerChange(): void
}

/**
 * Build the browser updater.
 *
 * Offline is the EXPECTED case, not an error: every failure path here is
 * silent. No console noise, no spinner, no user-visible failure — the player
 * simply keeps playing the version they have, which works completely.
 */
export const createWebUpdater = (deps: WebUpdaterDeps): WebUpdater => {
  let staged = false
  let applied = false
  // The last place the player was seen. Defaults to the most conservative
  // moment there is, so an update can never apply before the app has said
  // where the player actually is.
  let moment: UpdateMoment = 'inRun'
  let peers = 0

  /**
   * Try to swap. Called both when the app reports a new moment and when an
   * update finishes staging — a player sitting on the mode picker while the
   * download completes must not have to move to get their update.
   */
  const applyIfAllowed = (): void => {
    if (!decideApply({ staged, applied, moment, peers }).apply) return
    const worker = deps.waiting()
    // Belt and braces: `staged` implies this was non-null when we verified,
    // but the worker can be activated out from under us by another tab.
    if (worker === null) return
    applied = true
    // Hand over. The reload happens on `controllerchange`, NOT here — if the
    // swap never lands, the old version simply keeps running.
    worker.postMessage({ type: 'SKIP_WAITING' })
  }

  /** Promote a waiting worker to "staged" — but only if it verifies. */
  const stage = async (): Promise<CheckOutcome> => {
    if (staged) return 'already-staged'
    // No waiting worker = the install has not completed (or it failed and the
    // worker was discarded). Either way there is nothing whole to swap to.
    if (deps.waiting() === null) return 'downloading'

    let entries: readonly PrecacheEntry[]
    try {
      entries = await deps.precacheEntries()
    } catch {
      return 'incomplete' // unreadable cache → we know nothing → do nothing
    }
    if (!verifyPrecacheIntegrity(entries).ok) return 'incomplete'

    staged = true
    applyIfAllowed()
    return 'staged'
  }

  const check = async (): Promise<CheckOutcome> => {
    if (staged) return 'already-staged'
    let probe: HttpProbe
    try {
      probe = await deps.probe()
    } catch {
      return 'unavailable' // offline. Normal. Silent.
    }
    const version = parseVersionPayload(probe)
    if (version.kind === 'unavailable') return 'unavailable'
    if (!isNewerBuild(version.version, deps.appVersion)) return 'up-to-date'

    // There IS a newer build. Let the service worker do the downloading — it
    // is the thing that can do it atomically.
    try {
      await deps.checkForWorker()
    } catch {
      return 'unavailable'
    }
    return stage()
  }

  return {
    check,
    get staged(): boolean {
      return staged
    },
    reportMoment(next: UpdateMoment, nextPeers: number): void {
      moment = next
      peers = nextPeers
      applyIfAllowed()
    },
    onWorkerInstalled: stage,
    onControllerChange(): void {
      // Only reload for a swap WE asked for. A controller change we did not
      // initiate must never yank the page.
      if (applied) deps.reload()
    },
  }
}
