import { readFileSync, writeFileSync } from 'node:fs'
import {
  CENSUS_BUILDS,
  CENSUS_SEEDS,
  describeArenaRoom,
  FIGHT_TICKS,
  reachProbe,
  renderCensus,
  runFight,
  type FightResult,
  type ReachResult,
} from '../src/debug/census'
import { ARENAS } from '../src/game/arenas'
import { SIM_RATE } from '../src/game/types'

const args = process.argv.slice(2)
const flag = (name: string): string | undefined => {
  const i = args.indexOf(`--${name}`)
  if (i < 0) return undefined
  const value = args[i + 1]
  if (value === undefined || value.startsWith('--')) throw new Error(`--${name} needs a value`)
  return value
}
const list = (name: string): string[] | undefined => flag(name)?.split(',').filter(Boolean)

const arenas = list('arena') ?? Object.keys(ARENAS)
for (const a of arenas) if (!ARENAS[a]) throw new Error(`unknown arena "${a}"; known: ${Object.keys(ARENAS).join(', ')}`)
const wanted = list('build')
const builds = wanted ? CENSUS_BUILDS.filter((b) => wanted.includes(b.name)) : CENSUS_BUILDS
if (wanted && builds.length !== wanted.length) throw new Error(`unknown build in "${wanted.join(',')}"; known: ${CENSUS_BUILDS.map((b) => b.name).join(', ')}`)
const seeds = list('seeds')?.map(Number) ?? [...CENSUS_SEEDS]
if (seeds.length === 0 || !seeds.every((s) => Number.isInteger(s) && s >= 0)) throw new Error(`--seeds needs non-negative integers, got "${flag('seeds')}"`)
const unmodded = CENSUS_BUILDS.find((b) => b.name === 'none')!
const REACH_ARCHETYPE = 'gangster'
const reachDistances = args.includes('--no-reach') ? [] : [4, 5, 6, 7, 8, 9, 10, 11, 12]

const fights: FightResult[] = []
for (const arena of arenas) {
  for (const seed of seeds) {
    fights.push(runFight(arena, unmodded, seed, 'passive'))
    for (const b of builds) fights.push(runFight(arena, b, seed))
  }
  process.stderr.write(`census: ${arena} done (${fights.length} fights)\n`)
}
const reach: ReachResult[] = []
for (const d of reachDistances) for (const fires of [true, false]) reach.push(reachProbe(REACH_ARCHETYPE, seeds[0], d, fires))

const commandLine = `npx tsx scripts/census.mts ${args.join(' ')}`.trim()
const body = [
  `Generated by \`${commandLine}\`. Seeds ${seeds.join(', ')}; ${builds.length} builds; fights capped at ${FIGHT_TICKS / SIM_RATE} s.`,
  '',
  renderCensus({ arenas, seeds, rooms: seeds.map(describeArenaRoom), fights, reach, reachArchetype: REACH_ARCHETYPE }),
].join('\n')

const target = flag('write')
if (target) {
  const BEGIN = '<!-- census:begin -->'
  const END = '<!-- census:end -->'
  const doc = readFileSync(target, 'utf8')
  const i = doc.indexOf(BEGIN)
  const j = doc.indexOf(END)
  if (i < 0 || j < i) throw new Error(`${target} has no ${BEGIN} ... ${END} block to fill`)
  writeFileSync(target, `${doc.slice(0, i + BEGIN.length)}\n${body}\n${doc.slice(j)}`)
  process.stderr.write(`census: wrote ${target}\n`)
} else {
  console.log(body)
}
