// The side-effect tables in docs/design/substrate-census.md: bot teams of one
// and two against the bog-tide boss arenas, and players held in front of an NPC
// stun gunner, dry or flooded.
//
//   npx tsx scripts/substrate-probes.mts [--write docs/design/substrate-census.md]
import { readFileSync, writeFileSync } from 'node:fs'
import { CENSUS_BUILDS, CENSUS_SEEDS } from '../src/debug/census'
import { STUN_GUNNER_DIST, STUN_PROBE_TICKS, stunProbe, teamFight, type PlayerTally, type StunGround, type Team } from '../src/debug/substrateProbes'
import { SIM_RATE } from '../src/game/types'

const ARENAS = ['arena-bog-boss', 'arena-bog-boss-stock']
const BUILDS = ['none', 'shock', 'shock+pierce', 'seq shock', 'seq shock>frost', 'seq hand shock-lead', 'frost', 'incendiary', 'hand']
const TEAMS: Team[] = [1, 2]
const STUN_GROUNDS: StunGround[] = ['dry room', 'flooded room', 'flooded street']
const builds = BUILDS.map((name) => {
  const b = CENSUS_BUILDS.find((x) => x.name === name)
  if (!b) throw new Error(`unknown census build "${name}"`)
  return b
})

const sum = (xs: number[]): number => xs.reduce((a, b) => a + b, 0)
const perPlayer = (rows: PlayerTally[], key: keyof PlayerTally, team: Team, f: (xs: number[]) => string): string =>
  [...Array(team).keys()].map((i) => f(rows.map((r) => r[key][i]))).join(' / ')
const meanOf = (xs: number[]): string => String(Math.round(sum(xs) / xs.length))
const secsOf = (xs: number[]): string => (sum(xs) / SIM_RATE).toFixed(1)
const total = (xs: number[]): string => String(sum(xs))
const medianOf = (xs: number[]): number => {
  const s = [...xs].sort((a, b) => a - b)
  const m = Math.floor(s.length / 2)
  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2
}

const out: string[] = []
out.push('### Bot teams against the flooded lair', '')
out.push(
  `The census bot, alone or with a second bot one tile beside it, on seeds ${CENSUS_SEEDS.join(', ')}. Both players carry the build. Per-player columns read player 1 / player 2. Arc hits count electrocution damage events a player took; each is 20 hp. Shocked time is time spent electrified, summed over the seeds.`,
  '',
)
out.push('| arena | build | players | won | mean dmg taken | arc hits | shocked (s) |', '|---|---|---|---|---|---|---|')
for (const arena of ARENAS) {
  for (const b of builds) {
    for (const team of TEAMS) {
      const rows = CENSUS_SEEDS.map((seed) => teamFight(arena, b, seed, team))
      const won = rows.filter((r) => r.outcome === 'won').length
      out.push(`| ${arena} | ${b.name} | ${team} | ${won}/${rows.length} | ${perPlayer(rows, 'damage', team, meanOf)} | ${perPlayer(rows, 'arcHits', team, total)} | ${perPlayer(rows, 'shockedTicks', team, secsOf)} |`)
    }
  }
  process.stderr.write(`probes: ${arena} done\n`)
}
out.push('')

out.push('### An NPC stun gun against wet players', '')
out.push(
  `A gangster armed with a stun gun starts ${STUN_GUNNER_DIST} tiles from the players. The players hold still for ${STUN_PROBE_TICKS / SIM_RATE} s. A flooded room is the arena room under the bog tide (the experiment); a flooded street is an open street row under the tide, which floods in real bog-tide play. On flooded ground the players and the gunner are wet. Totals over seeds ${CENSUS_SEEDS.join(', ')}; per-player columns read player 1 / player 2.`,
  '',
)
out.push('| ground | players | stun shots | dmg taken | arc hits | shocked (s) | downed | median time to down (s) |', '|---|---|---|---|---|---|---|---|')
for (const ground of STUN_GROUNDS) {
  for (const team of TEAMS) {
    const rows = CENSUS_SEEDS.map((seed) => stunProbe(seed, ground, team))
    const downs = (i: number): number[] => rows.map((r) => r.downedAt[i]).filter((t): t is number => t !== undefined)
    const players = [...Array(team).keys()]
    const cells = [
      String(sum(rows.map((r) => r.shots))),
      perPlayer(rows, 'damage', team, total),
      perPlayer(rows, 'arcHits', team, total),
      perPlayer(rows, 'shockedTicks', team, secsOf),
      players.map((i) => `${downs(i).length}/${rows.length}`).join(' / '),
      players.map((i) => (downs(i).length ? (medianOf(downs(i)) / SIM_RATE).toFixed(1) : 'n/a')).join(' / '),
    ]
    out.push(`| ${ground} | ${team} | ${cells.join(' | ')} |`)
  }
}
process.stderr.write('probes: stun probe done\n')

const body = [`Generated by \`npx tsx scripts/substrate-probes.mts ${process.argv.slice(2).join(' ')}\`.`.replace(' `.', '`.'), '', ...out].join('\n')
const i = process.argv.indexOf('--write')
const target = i >= 0 ? process.argv[i + 1] : undefined
if (target) {
  const BEGIN = '<!-- probes:begin -->'
  const END = '<!-- probes:end -->'
  const doc = readFileSync(target, 'utf8')
  const a = doc.indexOf(BEGIN)
  const z = doc.indexOf(END)
  if (a < 0 || z < a) throw new Error(`${target} has no ${BEGIN} ... ${END} block to fill`)
  writeFileSync(target, `${doc.slice(0, a + BEGIN.length)}\n${body}\n${doc.slice(z)}`)
  process.stderr.write(`probes: wrote ${target}\n`)
} else {
  console.log(body)
}
